#ifndef QBUS_CONSTANT_H
#define QBUS_CONSTANT_H
// global config items
#define RD_KAFKA_CONFIG_BOOTSTRAP_SERVERS "bootstrap.servers"
#define RD_KAFKA_CONFIG_INTERNAL_TERMINATION_SIGNAL \
  "internal.termination.signal"
#define RD_KAFKA_CONFIG_QUEUE_BUFFERING_MAX_MS "queue.buffering.max.ms"
#define RD_KAFKA_CONFIG_GROUP_ID "group.id"
#define RD_KAFKA_CONFIG_ENABLE_AUTO_COMMIT "enable.auto.commit"
#define RD_KAFKA_CONFIG_TOPIC_METADATA_REFRESH_INTERVAL \
  "topic.metadata.refresh.interval.ms"
#define RD_KAFKA_CONFIG_CLIENT_ID "client.id"
#define RD_KAFKA_CONFIG_SOCKET_BLOCKING_MAX_MS "socket.blocking.max.ms"
#define RD_KAFKA_TOPIC_MESSAGE_RETRIES "message.send.max.retries"
#define RD_KAFKA_CONFIG_STATISTICS_INTERVAL_MS "statistics.interval.ms"

// topic config items
#define RD_KAFKA_TOPIC_CONFIG_AUTO_OFFSET_RESET "auto.offset.reset"

// sdk config items
#define RD_KAFKA_SDK_CONFIG_SYNC_SEND "send.sync"
#define RD_KAFKA_SDK_CONFIG_LOG_LEVEL "log.level"
#define RD_KAFKA_SDK_CONFIG_ENABLE_RD_KAFKA_LOG "enable.rdkafka.log"
#define RD_KAFKA_SDK_CONFIG_BROKER_LIST "broker.list"
#define RD_KAFKA_SDK_CONFIG_RECORD_MSG "enable.record.msg"
#define RD_KAFKA_SDK_CONFIG_PRODUCER_ENABLE_MINI_LATENCY \
  "minimize.produce.latency"
#define RD_KAFKA_SDK_CONSUMER_POLL_TIME "consumer.poll.time.ms"
#define RD_KAFKA_SDK_CONSUMER_MANUAL_COMMIT_TIME "manual.commit.time.ms"
#define RD_KAFKA_SDK_USER_MANUAL_COMMIT_OFFSET "user.manual.commit.offset"
#define RD_KAFKA_SDK_FORCE_DESTROY "force.destroy"

// config values
#define RD_KAFKA_SDK_CONFIG_ENABLE_RD_KAFKA_LOG_DEFAULT "false"
#define RD_KAFKA_SDK_CONFIG_LOG_LEVEL_DEFAULT "info"
#define RD_KAFKA_SDK_CONFIG_VALUE_SYNC_SEND_DEFAULT "false"
#define RD_KAFKA_SDK_CONFIG_VALUE_SYNC_SEND "true"
#define RD_KAFKA_CONFIG_QUEUE_BUFFERING_SYNC "1"
#define RD_KAFKA_TOPIC_CONFIG_AUTO_OFFSET_RESET_EARLIEST "earliest"
#define RD_KAFKA_CONSUMER_POLL_TIMEOUT_MS 100
#define RD_KAFKA_PRODUCE_ERROR_INIT_VALUE -12345
#define RD_KAFKA_PRODUCE_SYNC_SEND_POLL_TIMEOUT_MS 100
#define RD_KAFKA_TOPIC_MESSAGE_RETRIES_VALUE "7"
#define RD_KAFKA_CONFIG_STATISTICS_INTERVAL_MS_DEFAULT "60000"
#define RD_KAFKA_CONFIG_TOPIC_METADATA_REFRESH_INTERVAL_MS "30000"
#define RD_KAFKA_CONFIG_TOPIC_METADATA_REFRESH_INTERVAL_WHEN_SYNC_SEND_MS "300"
#define RD_KAFKA_CONFIG_CLIENT_ID_VALUE "QBus"
#define RD_KAFKA_SDK_CONFIG_RECORD_MSG_DEFAULT "false"
#define RD_KAFKA_SDK_CONFIG_PRODUCER_ENABLE_MINI_LATENCY_DEFAULT "false"
#define RD_KAFKA_SDK_MINIMIZE_PRODUCER_LATENCY_VALUE "1"
#define RD_KAFKA_POLL_TIMIE_OUT_MS 10
#define RD_KAFKA_SYNC_SEND_POLL_TIME 30
#define RD_KAFKA_SYNC_SEND_UINIT_POLL_TIME 300
#define RD_KAFKA_SDK_CONSUMER_POLL_TIME_DEFAULT_MS "100"
#define RD_KAFKA_SDK_MANUAL_COMMIT_TIME_DEFAULT_MS 200
#define RD_KAFKA_SDK_MANUAL_COMMIT_TIME_DEFAULT_MS_STR "200"
#define RD_KAFKA_SDK_USER_MANUAL_COMMIT_OFFSET_DEFAULT "false"
#define RD_KAFKA_SDK_FORCE_DESTROY_DEFAULT "false"
#endif  // ifndef QBUS_CONSTANT_H
